name: Run Detekt and unit tests

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
  push:
    branches-ignore:
      - develop
      - main
      - 'release/**'

jobs:
  run_detekt_and_unit_tests:
    name: Run Detekt and unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout source code
        uses: actions/checkout@v2.3.2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run lint
        run: ./gradlew lintStagingDebug

      - name: Run unit tests with Kover
        run: ./gradlew koverMergedHtmlReport

      - name: Archive code coverage reports
          uses: actions/upload-artifact@v2
          if: always()
          with:
            name: CodeCoverageReports
            path: build/reports/kover/merged/
